version: '3'
services:
  app:
    container_name: cometlabs
    restart: always
    build: .
    env_file:
      - .env
    ports: 
    - "${PORT}:${PORT}"
    external_links:
    - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - '27017:27017'
